"""Initial database setup

Revision ID: 1e2c55d9225f
Revises: 1cc78c8b43c1
Create Date: 2026-06-24 21:27:02.918421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1e2c55d9225f'
down_revision: Union[str, Sequence[str], None] = '1cc78c8b43c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emails',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('processed_emails', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name='emails_pk')
    )
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v7()'), nullable=False),
    sa.Column('idempotency_key', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('email', 'digest', 'webhook', name='notificationtype'), nullable=False),
    sa.Column('priority', sa.Enum('low', 'medium', 'high', 'critical', name='notificationpriority'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'failed', 'dead_lettered', 'delivered', name='notificationstatus'), nullable=False),
    sa.Column('recipient', sa.String(), nullable=True),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('body', sa.String(), nullable=True),
    sa.Column('webhook_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dead_lettered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('faliure_reason', sa.String(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name='notifications_pk'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index('idx_notifications_idempotency_key', 'notifications', ['idempotency_key'], unique=False)
    op.create_index('idx_notifications_type_status', 'notifications', ['type', 'status'], unique=False)
    op.create_index('idx_users_status_created_at', 'notifications', ['status', 'created_at'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v7()'), nullable=False),
    sa.Column('type', sa.Enum('email', 'github', 'google', name='usertype'), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('google_id', sa.String(), nullable=True),
    sa.Column('google_email', sa.String(), nullable=True),
    sa.Column('github_id', sa.String(), nullable=True),
    sa.Column('github_email', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name='users_pk'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('github_email'),
    sa.UniqueConstraint('google_email')
    )
    op.create_index('idx_users_email', 'users', ['email'], unique=False)
    op.create_index('idx_users_github_id', 'users', ['github_id'], unique=False)
    op.create_index('idx_users_google_id', 'users', ['google_id'], unique=False)
    op.create_table('api_keys',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v7()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='api_key_users_fk', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='api_keys_pk'),
    sa.UniqueConstraint('key')
    )
    op.create_index('idx_api_keys_key', 'api_keys', ['key'], unique=False)
    op.create_index('idx_api_keys_user_id', 'api_keys', ['user_id'], unique=False)
    op.create_table('otp',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v7()'), nullable=False),
    sa.Column('otp', sa.String(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('purpose', sa.Enum('email_signup', 'password_reset', name='otppurpose'), nullable=False),
    sa.Column('status', sa.Enum('valid', 'used', name='otpstatus'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='otp_user_id_fk', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='otp_id_pk'),
    sa.UniqueConstraint('otp')
    )
    op.create_index('idx_auth_otp', 'otp', ['otp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_auth_otp', table_name='otp')
    op.drop_table('otp')
    op.drop_index('idx_api_keys_user_id', table_name='api_keys')
    op.drop_index('idx_api_keys_key', table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_index('idx_users_google_id', table_name='users')
    op.drop_index('idx_users_github_id', table_name='users')
    op.drop_index('idx_users_email', table_name='users')
    op.drop_table('users')
    op.drop_index('idx_users_status_created_at', table_name='notifications')
    op.drop_index('idx_notifications_type_status', table_name='notifications')
    op.drop_index('idx_notifications_idempotency_key', table_name='notifications')
    op.drop_table('notifications')
    op.drop_table('emails')
    # ### end Alembic commands ###
