"""add status, delivered_at and failed_at columns to emails table

Revision ID: 7b088a910f87
Revises: 94eeb206588e
Create Date: 2026-06-30 02:14:08.224270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b088a910f87'
down_revision: Union[str, Sequence[str], None] = '94eeb206588e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emails', sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('emails', sa.Column('failed_at', sa.DateTime(timezone=True), nullable=True))
    sa.Enum('pending', 'delivered', 'failed', name='emailstatus').create(op.get_bind())
    op.add_column('emails', sa.Column('status', sa.Enum('pending', 'delivered', 'failed', name='emailstatus'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('emails', 'delivered_at')
    op.drop_column('emails', 'failed_at')
    op.drop_column('emails', 'status')
    sa.Enum('pending', 'delivered', 'failed', name='emailstatus').drop(op.get_bind())
    # ### end Alembic commands ###
