"""add webhook_endpoints table to db and failed_at column to notifications

Revision ID: 8675ab597a4b
Revises: 7b088a910f87
Create Date: 2026-06-30 14:20:01.515164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8675ab597a4b'
down_revision: Union[str, Sequence[str], None] = '7b088a910f87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('webhook_endpoints',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v7()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('endpoint', sa.String(), nullable=False),
    sa.Column('secret', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='webhook_user_id_fk', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='webhook_endpoints_pk'),
    sa.UniqueConstraint('endpoint'),
    sa.UniqueConstraint('secret')
    )
    op.create_index('idx_webhook_endpoints_id', 'webhook_endpoints', ['id', 'endpoint'], unique=False)
    op.create_index('idx_webhook_endpoints_user_id', 'webhook_endpoints', ['user_id', 'endpoint'], unique=False)
    op.add_column('notifications', sa.Column('failed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_webhook_endpoints_id', table_name='webhook_endpoints')
    op.drop_index('idx_webhook_endpoints_user_id', table_name='webhook_endpoints')
    op.drop_table('webhook_endpoints')
    op.drop_column('notifications', 'failed_at')
    # ### end Alembic commands ###
