"""change processed_emails column to string type from jsonb

Revision ID: 94eeb206588e
Revises: de7ab861988e
Create Date: 2026-06-29 13:26:10.219280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '94eeb206588e'
down_revision: Union[str, Sequence[str], None] = 'de7ab861988e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emails', sa.Column('processed_email', sa.String(), nullable=False))
    op.drop_column('emails', 'processed_emails')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emails', sa.Column('processed_emails', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_column('emails', 'processed_email')
    # ### end Alembic commands ###
