"""create composite index on api_keys

Revision ID: a5fa0b0e6101
Revises: 8675ab597a4b
Create Date: 2026-07-01 22:42:07.112899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5fa0b0e6101'
down_revision: Union[str, Sequence[str], None] = '8675ab597a4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_api_keys_key'), table_name='api_keys')
    op.drop_index(op.f('idx_api_keys_user_id'), table_name='api_keys')
    op.create_index('idx_api_keys', 'api_keys', ['key', 'user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_api_keys', table_name='api_keys')
    op.create_index(op.f('idx_api_keys_user_id'), 'api_keys', ['user_id'], unique=False)
    op.create_index(op.f('idx_api_keys_key'), 'api_keys', ['key'], unique=False)
    # ### end Alembic commands ###
