"""add payload column to notifications table

Revision ID: de7ab861988e
Revises: 1e2c55d9225f
Create Date: 2026-06-29 03:12:58.689568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'de7ab861988e'
down_revision: Union[str, Sequence[str], None] = '1e2c55d9225f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.drop_column('otp', 'purpose')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('otp', sa.Column('purpose', postgresql.ENUM('email_signup', 'password_reset', name='otppurpose'), autoincrement=False, nullable=False))
    op.drop_column('notifications', 'payload')
    # ### end Alembic commands ###
